services:
  db:
    image: postgres:17-alpine
    container_name: db-container
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: docker-aula
    ports:
      # Mapeia a porta externa 5433 (host) para a 5432 (container)
      - "5433:5432"  
    volumes:
      - meu-volume:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    networks:
      - minha-rede

  server:
    build:
      context: ./server
    container_name: server-container
    ports:
      - "3001:3000"
    environment:
      PORT: 3000
      DB_HOST: db # o nome do serviço "db" funciona como hostname
      DB_USER: postgres
      DB_PASSWORD: 123
      DB_NAME: docker-aula
      DB_PORT: 5432 # Dentro do container, a porta do Postgres é 5432
      NODE_ENV: production
    depends_on:
      - db
    networks:
      - minha-rede

  # Exercício 1
  frontum:
    build: ./front-um
    container_name: um-container
    ports:
      - "3002:80"
    networks:
      - minha-rede
    depends_on:
      - server

  # Exercício 2
  frontdois:
    build: ./front-dois
    container_name: dois-container
    ports:
      - "3003:80"
    networks:
      - minha-rede
    depends_on:
      - server

volumes:
  meu-volume:

networks:
  minha-rede:
    driver: bridge