# Utiliza imagem base do Nginx
FROM nginx:alpine

# Copia arquivos estáticos para o diretório padrão do Nginx
COPY index.html /usr/share/nginx/html/
COPY style.css /usr/share/nginx/html/
COPY script.js /usr/share/nginx/html/
